config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "games#new"
  resources :games
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/game.rb
class Game < ApplicationRecord
  validates :player_1, :player_2, :status, presence: true
  enum status: { running: 0, finished: 1 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :get_game, only: %i[ edit ]

  def index
    @game = Game.find params[:format]
    if params[:game_info] == 'draw'
      @game.winner = 'draw'
    else
      @game.winner = params[:game_info] == 'X' ? @game.player_1 : @game.player_2
    end
    @game.status = 'finished'
    @game.save
    redirect_to new_game_path
  end

  def new
    @game = Game.new
  end

  def create
    @game = Game.new(game_params)
    @game.status = "running"

    if @game.save
      redirect_to edit_game_path(@game), notice: "Game started successfully"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  private

  def game_params
    params.require(:game).permit(:player_1, :player_2)
  end

  def get_game
    @game = Game.find params[:id]
    redirect_to new_game_path unless @game
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/games/edit.html.erb
<div class='row'>
  <div class='col-lg-5 border rounded mx-auto'>
    <div class='h5 ms-2 mt-1'>
      Player 1: <%= @game.player_1%> ('X')
    </div>
  </div>
  <div class='col-lg-5 border rounded mx-auto'>
    <div class='h5 ms-2 mt-1'>
      Player 2: <%= @game.player_2%> ('O')
    </div>
  </div>
</div>
<div class='mt-4' id="gameContainer">
  <div id="cellContainer" class="d-grid gap-2">
    <div cellIndex="0" class="cell btn btn-outline-secondary"></div>
    <div cellIndex="1" class="cell btn btn-outline-secondary"></div>
    <div cellIndex="2" class="cell btn btn-outline-secondary"></div>
    <div cellIndex="3" class="cell btn btn-outline-secondary"></div>
    <div cellIndex="4" class="cell btn btn-outline-secondary"></div>
    <div cellIndex="5" class="cell btn btn-outline-secondary"></div>
    <div cellIndex="6" class="cell btn btn-outline-secondary"></div>
    <div cellIndex="7" class="cell btn btn-outline-secondary"></div>
    <div cellIndex="8" class="cell btn btn-outline-secondary"></div>
  </div>
  <h2 id="statusText" class="mt-3"></h2>
  <button id="restartBtn" class="btn btn-primary">Restart</button>
</div>
<script>
  const cells = document.querySelectorAll(".cell");
  const statusText = document.querySelector("#statusText");
  const restartBtn = document.querySelector("#restartBtn");
  const winConditions = [
      [0, 1, 2],
      [3, 4, 5],
      [6, 7, 8],
      [0, 3, 6],
      [1, 4, 7],
      [2, 5, 8],
      [0, 4, 8],
      [2, 4, 6]
  ];
  let options = ["", "", "", "", "", "", "", "", ""];
  let currentPlayer = "X";
  let running = false;

  initializeGame();

  function initializeGame(){
      cells.forEach(cell => cell.addEventListener("click", cellClicked));
      restartBtn.addEventListener("click", restartGame);
      statusText.textContent = `${currentPlayer}'s turn`;
      running = true;
  }
  function cellClicked(){
      const cellIndex = this.getAttribute("cellIndex");

      if(options[cellIndex] != "" || !running){
          return;
      }

      updateCell(this, cellIndex);
      checkWinner();
  }
  function updateCell(cell, index){
      options[index] = currentPlayer;
      cell.textContent = currentPlayer;
  }
  function changePlayer(){
      currentPlayer = (currentPlayer == "X") ? "O" : "X";
      statusText.textContent = `${currentPlayer}'s turn`;
  }
  function checkWinner(){
      let roundWon = false;

      for(let i = 0; i < winConditions.length; i++){
          const condition = winConditions[i];
          const cellA = options[condition[0]];
          const cellB = options[condition[1]];
          const cellC = options[condition[2]];

          if(cellA == "" || cellB == "" || cellC == ""){
              continue;
          }
          if(cellA == cellB && cellB == cellC){
              roundWon = true;
              break;
          }
      }

      if(roundWon){
          statusText.textContent = `${currentPlayer} wins!`;
          running = false;
          saveGameDetails(currentPlayer)
      }
      else if(!options.includes("")){
          statusText.textContent = `Draw!`;
          running = false;
          saveGameDetails('draw')
      }
      else{
          changePlayer();
      }
  }
  function restartGame(){
    currentPlayer = "X";
    options = ["", "", "", "", "", "", "", "", ""];
    statusText.textContent = `${currentPlayer}'s turn`;
    cells.forEach(cell => cell.textContent = "");
    running = true;
  }
  function saveGameDetails(gameData) {
    fetch('<%= games_path(@game) %>?game_info=' + encodeURIComponent(gameData))
      .then(response => {
        if (response.redirected) {
          // Redirect to the specified location
          window.location.href = response.url;
        }
      })
      .catch(error => console.error('Error:', error));
  }
</script>

app/views/games/new.html.erb
<div class="container mt-4">
  <h3>Start New Game!!!</h3>
  <%= form_with(model: @game, local: true) do |form| %>
    <% if @game.errors.any? %>
      <div id="error_explanation">
        <h4>Errors:</h4>
        <ul>
          <% @game.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="mb-3">
      <%= form.label :player_1, class: 'form-label' %>
      <%= form.text_field :player_1, class: 'form-control' %>
    </div>
    <div class="mb-3">
      <%= form.label :player_2, class: 'form-label' %>
      <%= form.text_field :player_2, class: 'form-control' %>
    </div>
    <%= form.submit "Start Game", class: 'btn btn-primary' %>
  <% end %>
</div>
<div class="container mt-4">
  <h1 class="mb-4">Game Info</h1>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Player 1</th>
        <th scope="col">player 2</th>
        <th scope="col">Winner</th>
        <th scope="col">Date</th>
      </tr>
    </thead>
    <tbody>
      <% Game.where(status: 1).order(created_at: :desc).each do |game| %>
        <tr>
          <td><%= game.player_1 %></td>
          <td><%= game.player_2 %></td>
          <td><%= game.winner %></td>
          <td><%= game.created_at %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TicTacToeGame</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <div class='container-fluid'>
      <div class='row'>
        <div class='col-lg-8 mx-auto'>
          <div class='card'>
            <div class='card-header text-center'>
              <h2>!!! TicTacToe !!!</h2>
            </div>
            <div class='card-body'>
              <div class='row'>
                <div class='col-6 mx-auto'>
                  <%= yield %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </body>
  </html>